const STATES = {
    'nationwide': 'Nationwide', 
    'al': 'Alabama',
    'ak': 'Alaska',
    'az': 'Arizona',
    'ar': 'Arkansas',
    'ca': 'California',
    'co': 'Colorado',
    'ct': 'Connecticut',
    'dc': 'DC',
    'de': 'Delaware',
    'fl': 'Florida',
    'ga': 'Georgia',
    'hi': 'Hawaii',
    'id': 'Idaho',
    'il': 'Illinois',
    'in': 'Indiana',
    'ia': 'Iowa',
    'ks': 'Kansas',
    'ky': 'Kentucky',
    'la': 'Louisiana',
    'me': 'Maine',
    'md': 'Maryland',
    'ma': 'Massachusetts',
    'mi': 'Michigan',
    'mn': 'Minnesota',
    'ms': 'Mississippi',
    'mo': 'Missouri',
    'mt': 'Montana',
    'ne': 'Nebraska',
    'nv': 'Nevada',
    'nh': 'New Hampshire',
    'nj': 'New Jersey',
    'nm': 'New Mexico',
    'ny': 'New York',
    'nc': 'North Carolina',
    'nd': 'North Dakota',
    'oh': 'Ohio',
    'ok': 'Oklahoma',
    'or': 'Oregon',
    'pa': 'Pennsylvania',
    'ri': 'Rhode Island',
    'sc': 'South Carolina',
    'sd': 'South Dakota',
    'tn': 'Tennessee',
    'tx': 'Texas',
    'ut': 'Utah',
    'vt': 'Vermont',
    'va': 'Virginia',
    'wa': 'Washington',
    'wv': 'West Virginia',
    'wi': 'Wisconsin',
    'wy': 'Wyoming'
}

const ATTRIBUTES = {
    "1": "Title",
    "2": "Description",
    "8": "Bedroom",
    "9": "Bathroom",
    "10": "City",
    "12": "State",
    "19": "Square footage",
    "21": "Monthly rent",
    "22": "Asking price",
    "23": "Year built",
    "25": "Security deposit",
    "26": "Minimal lease term",
    "28": "Acreage",
    "30": "Street address",
    "31": "Represented by",
    "33": "Zip code",
    "35": "Homeowner association fee",
    "36": "Condo fee",
    "39": "Pet policy",
    "41": "Other amenities",
    "42": "Parking spaces",
    "43": "School",
    "46": "Basement",
    "49": "Neighborhood",
    "50": "Contact name",
    "51": "Contact phone",
    "52": "County",
    "55": "Brokerage company",
    "56": "MLS ID",
    "57": "Lot size",
    "60": "Interior",
    "61": "Exterior",
    "62": "Rent includes",
    "63": "Lot developed",
    "65": "Owner financing available",
    "66": "Kitchen and dining",
    "67": "Bed and bath",
    "68": "Community",
    "69": "Building amenities",
    "70": "Pet policy",
    "74": "Special offer"
}

const CATEGORY_URIS = {
    3001: 'single-family-home-for-rent',
    3002: 'townhouse-for-rent',
    3003: 'apartment',
    3004: 'condominium-for-rent',
    2007: 'roommate',
    3011: 'single-family-home-for-sale',
    3012: 'townhouse-multi-unit-for-sale',
    3013: 'condominium-for-sale',
    3014: 'manufactured-home-for-sale',
    1006: 'lease-purchase',
    3015: 'land-for-sale',
    2011: 'vacation-rental'
}

function attributeName(attributeId) {
    return ATTRIBUTES[attributeId]
}

const LOOKUPS = {
    "MOM": "Master on main",
    "GOM": "Guest suite on main",
    "ILS": "In-law suite",
    "SSM": "Separate shower in master bath",
    "WIC": "Walk-in closet in master",
    "JT": "Jacuzzi tub",
    "RFG": "Refrigerator",
    "DW": "Dishwasher",
    "GD": "Garbage disposal",
    "RO": "Range/oven",
    "BA": "Breakfast area(nook)",
    "GCS": "Granite countertops",
    "FDG": "Formal dining room",
    "FUR": "Furnished",
    "WD": "Washer and dryer",
    "WDH": "Washer/dryer connection",
    "LR": "Laundry room",
    "FP": "Fireplace",
    "HW": "Hardwood floor",
    "CM": "Crown molding",
    "TZA": "2-zone AC/heating",
    "PKG": "Parking",
    "PARKING1": "1-car parking space",
    "PARKING2": "2-car parking space",
    "G1": "1-car garage",
    "G2": "2-car garage",
    "G3": "3-car garage",
    "FB": "Fenced backyard",
    "PSP": "Private swimming pool",
    "PT": "Patio",
    "DK": "Deck",
    "BLY": "Balcony",
    "FPCH": "Front porch",
    "IS": "Irrigation system",
    "CDS": "Cul-de-sac",
    "CCG": "24 Hour Concierge",
    "CP": "Children's playroom",
    "OSP": "On-site parking",
    "GC": "Gated community",
    "FC": "Fitness center",
    "CH": "Club house",
    "SSP": "Shared swimming pool",
    "TT": "Tennis",
    "BB": "Basketball",
    "PGD": "Playground",
    "GLF": "Golf",
    "PRK": "Close to park",
    "HBT": "Hiking/biking trails",
    "PTR": "Public transportation",
    "WT": "Water and sewer",
    "ELC": "Electricity",
    "GAS": "Gas",
    "GP": "Garbage pickup",
    "NOFEE": "No broker fee",
    "EXC": "Exclusive",
    "DOORMAN": "Doorman",
    "ELEVATOR": "Elevator",
    "CAT": "Cats",
    "DOG1": "Dogs (under 25 lbs)",
    "DOG2": "Large Dogs",
    "EIK": "Eat in kitchen or dining",
    "HPI": "High speed internet",
    "TF": "Top floor",
    "GF": "Ground floor",
    "LRF": "Laundry facilities",
    "GGP": "Garage parking",
    "STS": "Storage Space(s)",
    "WCA": "Wheelchair Access",
    "DMN": "Doorman",
    "BIZ": "business center",
    "LKF": "Lake front",
    "BV": "Beach view",
    "OV": "Ocean view",
    "WV": "Water view",
    "MTV": "Mountain view",
    "FK": "Full kitchen",
    "MV": "Microwave",
    "CU": "Cooking utensils",
    "IC": "Ice maker",
    "CFM": "Coffee maker",
    "LN": "Linens provided",
    "AC": "Air conditioning",
    "CF": "Ceiling fans",
    "HT": "Hot tub",
    "SNA": "Sauna",
    "BNY": "Balcony",
    "DCK": "Dock",
    "TV": "Cable/Satellite TV",
    "PC": "Computer",
    "WB": "Internet",
    "WF": "WiFi",
    "CR": "Conference room",
    "LT": "Live theater",
    "MUS": "Museums",
    "SRF": "Surfing",
    "SAL": "Sailing",
    "SDS": "Scuba diving/snorkeling",
    "KYK": "Kayaking",
    "PRS": "Parasailing",
    "SKI": "Skiing",
    "SNB": "Snowboarding",
    "SNM": "Snowmobiling",
    "ISK": "Ice skating",
    "SLT": "Sledding/Tubing",
    "FS": "Fishing",
    "BOT": "Boating",
    "RFT": "Rafting",
    "HOR": "Horseback riding",
    "ROC": "Rock climbing",
    "LF": "Lake front",
    "LK": "Lake",
    "SP": "Private swimming pool",
    "SPP": "Shared swimming pool",
    "STC": "Swimming/tennis community"
}

export { STATES, CATEGORY_URIS, attributeName, LOOKUPS }